#!/usr/bin/env python3
import math, re

def addition(cond):
    '''
    addition
    -
    core.calculate.addition
    '''
    cond = cond.replace(" ", "")
    cond = [int(x) for x in cond.split('+')]
    return sum(cond)


def read(target):
    return list(filter(None, open(target).read().split('\n')))


class fx:
    @staticmethod
    def trigonometry(object):
        '''
        trigonometry function set
        ---
        core.fx.trigonometry
        '''
        object = [x.replace('sin', 'math.sin') for x in object]
        object = [x.replace('cos', 'math.cos') for x in object]
        object = [x.replace('tan', 'math.tan') for x in object]
        return object

    def trignometricFunctionAuto(object):
        if (f'sin{i}' in object[z - 1]):
            object = [x.replace('sin', 'math.sin') for x in object]

    @staticmethod
    def translate_legacy(object, z):
        '''
        translate <- legacy
        ---
        core.fx.translate_legacy
        '''

        while z < len(object):
            q = 0

            try:
                while q < len(object[z]):
                    i = 0

                    try:
                        place = [n for n in range(len(object[z])) if object[z][n:n + 2] == ')(']
                        object[z] = f'{object[z][:place[q] + 1]}*{object[z][place[q] + 1:]}'

                    except IndexError:
                        pass


                    while i < 10:
                        try:
                            place = [n for n in range(len(object[z])) if object[z][n:n + 2] == f'{i}(']
                            object[z] = f'{object[z][:place[q] + 1]}*{object[z][place[q] + 1:]}'

                            place = [n for n in range(len(object[z])) if object[z][n:n + 2] == f'){i}']
                            object[z] = f'{object[z][:place[q] + 1]}*{object[z][place[q] + 1:]}'

                        except IndexError:
                            pass

                        i += 1
                    q += 1
                    z += 1

            except IndexError:
                pass

    @staticmethod
    def translate(object, z):
        '''
        translate
        ---
        core.fx.translate
        '''
        for i in range(10):
            object = [x.replace(f'{i}(', f'{i}*(') for x in object]
            object = [x.replace(f'){i}', f')*{i}') for x in object]

            object = [x.replace(f'{i}sin', f'{i}*sin') for x in object]
            object = [x.replace(f'{i}cos', f'{i}*cos') for x in object]
            object = [x.replace(f'{i}tan', f'{i}*tan') for x in object]

        object = [x.replace(f'^', f'**') for x in object]

        return object

    def accuFloat():
        rePattern = r'[-+]? (?: (?: \d* \. \d+ ) | (?: \d+ \.? ) )(?: [Ee] [+-]? \d+ ) ?'
        rx = re.compile(rePattern, re.VERBOSE)
        objet = rx.findall(f"{object}")
        for i in range(len(objet)):
            objet[i]


out = []
def output(result):
    out.append(result)


def compile(target):
    '''
    compile
    -
    core.compile
    '''

    object = read(target)
    z = 0

    #fx.translate(object, z)
    #object = fx.trigonometry(object)

    while z < len(object):

        if (' calculate ' in ' '+object[z]+' ') or (' calc ' in ' '+object[z]+' '):
            output(eval(f'{object[z - 1]}'))

        z += 1
        
    if z == len(object):
        z = 0

    while z < len(out):
        print(out[z])
        z += 1


object = []
def instant(input):
    '''
    compile
    -
    core.instant
    '''

    global object
    object.append(input)
    z = 0

    while z < len(object):
        
        if (' illegalInputTestString ' in ' '+object[z]+' ') or (' a@a.com ' in ' '+object[z]+' '):
            output(eval(f'{object[z - 1]}'))

        if 'calc' == object[z]:
            object = fx.translate(object, z)
            object = fx.trigonometry(object)
            
            output(eval(f'{object[z - 1]}'))

        z += 1


    if z == len(object):
        z = 0

    while z < len(out):
        print(out[z])
        z += 1
        object.clear()
        out.clear()


live = 0
written = 0

while live == 1:
    try:
        x = input('> ')
        if x:
            instant(x)

    except IndexError or ValueError:
        print("Fix inserted formula")

    except NameError:
        object.clear()
        print('No value returned')


while written == 1:
    compile('test.math')
    break


print(str(fx.accuFloat))